Repository cambridge-stacker/cambridge, pull requests merged in 2025-06, with the labels that each got.

#15 Fixed history_6rolls_35bag.lua for real.
  tetris/randomizers/history_6rolls_35bag.lua
Labels: bug, 0.4.x

#4 v0.4.x Experiment: Toasts!
  load/version.lua
  main.lua
  scene/config.lua
  scene/replay.lua
  scene/replay_select.lua
Labels: enhancement, 0.4.x

#11 correct regret timings (new research!)
  tetris/modes/survival_a3.lua
Labels: bug, 0.3.x

#13 Added tags to all the main modes
  .vscode/settings.json
  tetris/modes/big_a1.lua
  tetris/modes/big_a2.lua
  tetris/modes/marathon_2020.lua
  tetris/modes/marathon_a1.lua
  tetris/modes/marathon_a2.lua
  tetris/modes/marathon_a3.lua
  tetris/modes/phantom_mania.lua
  tetris/modes/phantom_mania2.lua
  tetris/modes/phantom_mania_n.lua
  tetris/modes/race_40.lua
  tetris/modes/sakura.lua
  tetris/modes/strategy.lua
  tetris/modes/survival_2020.lua
  tetris/modes/survival_a1.lua
  tetris/modes/survival_a2.lua
  tetris/modes/survival_a3.lua
  tetris/modes/survival_ax.lua
Labels: enhancement, 0.4.x

#18 Edited user-facing strings for language consistency and conciseness
  .gitignore
  main.lua
  scene/audio_config.lua
  scene/game_config.lua
  scene/key_config.lua
  scene/replay_select.lua
  scene/stick_config.lua
  scene/title.lua
  scene/tuning.lua
  scene/tutorial_keybinder.lua
  scene/visual_config.lua
  tetris/rulesets/arika.lua
  tetris/rulesets/arika_ace.lua
  tetris/rulesets/arika_ace2.lua
  tetris/rulesets/arika_exp.lua
  tetris/rulesets/arika_ti.lua
  tetris/rulesets/standard.lua
  tetris/rulesets/standard_ace.lua
  tetris/rulesets/standard_exp.lua
  tetris/rulesets/standard_ti.lua
Labels: 0.4.x
